### ISSUE TITLE
css 元素的属性继承

### ISSUE THREAD

**Issue by CongratulateWE** [CongratulateWE/NoteBook#10]

**Comment by CongratulateWE** [comment]
font-weight 的继承属性，但是不知道为什么在活动中发现没有完成继承。原因应该是reset.css中设置了默认的font-weight: normal，优先级高于继承。

```html
<div class="outer">
  一段外部文字
  <div class="inner">
     一段内部文字
     <p>test</p>
  </div>
</div>
```
```css
.outer {
  color: red;
  font-weight: 700;
}

.inner {
  color: #000;
  /* font-weight: bold; */
}

p {
  /* font-weight: normal; */
}
```
