### ISSUE TITLE
hover 显示详情

### ISSUE THREAD

**Issue by CongratulateWE** [CongratulateWE/NoteBook#86]
类似于下面这种形式的展示
<img src="https://user-images.githubusercontent.com/11611753/113960199-af43d600-9856-11eb-9287-97ac3636df6d.png" width="500">

我想的是用在后台页面上添加一些提示信息，也类似于思维导图里的批注，点击才能查看，否则就只有一个icon也不占多少空间。

```html
<div class="outer">
  <div class="icon"></div>
  <div class="details">
    这里显示帮助信息
  </div>
</div>
```
```css
.icon {
  width: 50px;
  height: 50px;
  background: red;
}

.details {
  display: none;  
}

.icon:hover + .details {
  display: block;
}
```

https://codepen.io/Moonzno/pen/wvgrNrv

这应该是一个思路，帮助信息应该避免影响其他元素的布局
